version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 0.0.0.0:9200:9200
      - 0.0.0.0:9300:9300
volumes:
  data:
    driver: local